In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

# Data Sources and Selected Variables

For each year, data was retrieved from table 3. For the years 2020–2022, the data was supplemented with information from table 4, where the variables total sought places and total granted places were summed per case number before being joined with the main table.

Additionally, all Swedish column names were renamed to English during data processing to improve readability and consistency throughout the analysis.

### Variables Used in the Analysis

### The following variables are available for all years:

- *diarienummer* - case_number
- *utbildningsnamn* - education_name
- *utbildningsområde* - education_area
- *beslut* - decision
- *kommun* - municipality
- *län* - county
- *yh_poäng* - education_credits
- *studieform* - study_mode
- *studietakt_procent* - study_pace_percentage
- *utbildningsanordnare* - education_provider
- *huvudmannatyp* - principal_type

### The following two variables were retrieved from table 4 for the years 2020–2022 and from table 3 for the remaining years:

- *sökta_platser_totalt* - total_sought_places
- *beviljade_platser_totalt* - total_granted_places

### The following variables are only available for the years 2023–2025:

- *sun5_inriktning* - sun5_code
- *sun5_inriktning_namn* - sun5_name
- *seqf_nivå* - seqf_level
- *smalt_yrkesområde* - narrow_occupational_area

### The following variables were created during data processing for all years:

- source_year
- source_file
- source_sheet

The variables were selected to enable analyses of the development of the education supply over time, the geographical distribution of educations, different education areas and providers, as well as the relationship between the number of sought and granted education places.

### Create DataFrame for each year

In the first step, separate DataFrames were created for each year by selecting the variables that would be used in the analysis. The result was the following DataFrames:
- resultat_2020
- resultat_2021
- resultat_2022
- resultat_2023
- resultat_2024
- resultat_2025

# 2020

In [6]:
resultat_2020 = pd.read_excel("data/resultat-ansokningsomgang-2020.xlsx", sheet_name=5)

resultat_2020.sample(10)
resultat_2020.info()

,Utbildningsområde,Utbildningsnamn,Län,Kommun,Flera studiekommuner,Antal studiekommuner,Antal län,YH-poäng,Studieform,Studietakt %,Utbildningsanordnare administrativ enhet,Huvudmannatyp,Sökta platser per utbildningsomgång,Sökta platser totalt,Beviljade platser per utbildningsomgång,Beviljade platser totalt,Diarienummer,Beslut
785,"Ekonomi, administration och försäljning",Tech-rekryterare,Västra Götaland,Mölndal,Nej,1,1,320,Bunden,100,Campus Mölndal,Kommun,30,90,0,0,MYH 2020/5607,Ej beviljad
709,"Ekonomi, administration och försäljning",Onlinemarknadsförare,Västra Götaland,Göteborg,Nej,1,1,320,Bunden,100,Medieinstitutet i Sverige AB,Privat,35,105,0,0,MYH 2020/5694,Ej beviljad
1070,Hälso- och sjukvård samt socialt arbete,Tandsköterska,Skåne,Kristianstad,Nej,1,1,325,Bunden,100,"Kristianstad kommun, Vuxenutbildningen",Kommun,28,112,28,112,MYH 2020/4983,Beviljad
175,Data/IT,IoT-utvecklare,Norrbotten,Arjeplog,Ja,7,5,400,Bunden,100,Företagsekonomiska Institutet 1888 AB,Privat,5,15,0,0,MYH 2020/5787,Ej beviljad
1311,Samhällsbyggnad och byggteknik,Byggnadsingenjör - Produktion,Stockholm,Solna,Nej,1,1,400,Bunden,100,Hermods AB Stockholm,Privat,30,120,0,0,MYH 2020/4340,Ej beviljad
1024,Hälso- och sjukvård samt socialt arbete,Specialistutbildad undersköterska med inriktni...,Västmanland,Västerås,Nej,1,1,215,Distans,50,Svensk vård och kompetensutveckling i Stockhol...,Privat,30,90,0,0,MYH 2020/5520,Ej beviljad
1312,Samhällsbyggnad och byggteknik,Byggnadsingenjör - Produktion,Västerbotten,Umeå,Nej,1,1,400,Distans,100,Hermods AB Umeå,Privat,30,120,30,90,MYH 2020/3719,Beviljad
614,"Ekonomi, administration och försäljning",IT-Rekryterare,Västra Götaland,Göteborg,Nej,1,1,300,Distans,100,IT-Högskolan Sverige AB,Privat,35,105,0,0,MYH 2020/5861,Ej beviljad
1341,Samhällsbyggnad och byggteknik,Byggprojektör BIM,Kronoberg,Växjö,Nej,1,1,400,Bunden,100,EC Utbildning AB Växjö,Privat,30,90,0,0,MYH 2020/5553,Ej beviljad
1018,Hälso- och sjukvård samt socialt arbete,Specialistutbildad undersköterska inom vård av...,Gävleborg,Hofors,Nej,1,1,225,Distans,50,Omsorgsförlaget,Privat,35,175,0,0,MYH 2020/5638,Ej beviljad

<class 'pandas.DataFrame'>
RangeIndex: 1903 entries, 0 to 1902
Data columns (total 18 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Utbildningsområde                         1903 non-null   str
 1   Utbildningsnamn                           1903 non-null   str
 2   Län                                       1903 non-null   str
 3   Kommun                                    1903 non-null   str
 4   Flera studiekommuner                      1903 non-null   str
 5   Antal studiekommuner                      1903 non-null   int64
 6   Antal län                                 1903 non-null   int64
 7   YH-poäng                                  1903 non-null   int64
 8   Studieform                                1903 non-null   str
 9   Studietakt %                              1903 non-null   int64
 10  Utbildningsanordnare administrativ enhet  1903 non-null   str
 11  Huvudmannatyp                             1903 non-null   str
 12  Sökta platser per utbildningsomgång       1903 non-null   int64
 13  Sökta platser totalt                      1903 non-null   int64
 14  Beviljade platser per utbildningsomgång   1903 non-null   int64
 15  Beviljade platser totalt                  1903 non-null   int64
 16  Diarienummer                              1903 non-null   str
 17  Beslut                                    1903 non-null   str
dtypes: int64(8), str(10)
memory usage: 533.5 KB

# 2021

In [7]:
resultat_2021 = pd.read_excel("data/resultat-ansokningsomgang-2021.xlsx", sheet_name=5)

resultat_2021.sample(10)
resultat_2021.info()

,Utbildningsområde,Utbildningsnamn,Län,Kommun,Flera studiekommuner,Antal kommuner,Antal län,YH-poäng,Studieform,Studietakt %,...,Sökta platser per utbildningsomgång,Sökta platser totalt,Beviljade platser utbildningsomgång 1,Beviljade platser utbildningsomgång 2,Beviljade platser utbildningsomgång 3,Beviljade platser utbildningsomgång 4,Beviljade platser utbildningsomgång 5,Beviljade platser totalt,Diarienummer,Beslut
1447,Teknik och tillverkning,Marin servicetekniker,Skåne,Malmö,Ja,6,5,300,Bunden,100,...,7,35,0.0,0,0,0,0,0.0,MYH 2021/4430,Ej beviljad
32,Data/IT,BI-Analyst med AI-kompetens,Västra Götaland,Uddevalla,Nej,1,1,400,Distans,100,...,30,90,30.0,30,30,.,.,90.0,MYH 2021/4084,Beviljad
846,Hälso- och sjukvård samt socialt arbete,Specialistundersköterska Demensvård,Örebro,Örebro,Nej,1,1,235,Distans,50,...,35,175,35.0,35,35,0,0,105.0,MYH 2021/3213,Beviljad
589,"Ekonomi, administration och försäljning",Payroll Business Partner,Skåne,Malmö,Nej,1,1,410,Bunden,100,...,35,105,35.0,35,35,.,.,105.0,MYH 2021/4348,Beviljad
1349,Teknik och tillverkning,Bagare och Konditor,Uppsala,Uppsala,Nej,1,1,215,Bunden,100,...,30,90,0.0,0,0,.,.,0.0,MYH 2021/3266,Ej beviljad
38,Data/IT,Blockchain Business Developer,Norrbotten,Boden,Ja,2,2,400,Bunden,100,...,10,20,0.0,0,.,.,.,0.0,MYH 2021/3631,Ej beviljad
371,"Ekonomi, administration och försäljning",Affärsutvecklare inriktning digitalisering och...,Västra Götaland,Göteborg,Nej,1,1,400,Distans,100,...,35,105,0.0,0,0,.,.,0.0,MYH 2021/4224,Ej beviljad
708,"Hotell, restaurang och turism",Gastronomiprogrammet - kök och matsal,Västerbotten,Vilhelmina,Ja,2,2,200,Distans,100,...,20,60,0.0,0,0,.,.,0.0,MYH 2021/4329,Ej beviljad
920,Hälso- och sjukvård samt socialt arbete,Tandsköterska,Jönköping,Jönköping,Ja,2,1,325,Bunden,100,...,20,100,20.0,20,20,20,0,80.0,MYH 2021/3111,Beviljad
1219,Samhällsbyggnad och byggteknik,Mätningstekniker,Västernorrland,Kramfors,Nej,1,1,415,Bunden,100,...,20,60,20.0,20,20,.,.,60.0,MYH 2021/3797,Beviljad

<class 'pandas.DataFrame'>
RangeIndex: 1586 entries, 0 to 1585
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Utbildningsområde                         1586 non-null   str
 1   Utbildningsnamn                           1586 non-null   str
 2   Län                                       1586 non-null   str
 3   Kommun                                    1586 non-null   str
 4   Flera studiekommuner                      1586 non-null   str
 5   Antal kommuner                            1586 non-null   int64
 6   Antal län                                 1586 non-null   int64
 7   YH-poäng                                  1586 non-null   int64
 8   Studieform                                1586 non-null   str
 9   Studietakt %                              1586 non-null   int64
 10  Typ av examen                             1586 non-null   str
 11  Utbildningsanordnare administrativ enhet  1586 non-null   str
 12  Huvudmannatyp                             1586 non-null   str
 13  Sökta platser per utbildningsomgång       1586 non-null   int64
 14  Sökta platser totalt                      1586 non-null   int64
 15  Beviljade platser utbildningsomgång 1     1586 non-null   float64
 16  Beviljade platser utbildningsomgång 2     1586 non-null   object
 17  Beviljade platser utbildningsomgång 3     1586 non-null   object
 18  Beviljade platser utbildningsomgång 4     1586 non-null   object
 19  Beviljade platser utbildningsomgång 5     1586 non-null   object
 20  Beviljade platser totalt                  1586 non-null   float64
 21  Diarienummer                              1586 non-null   str
 22  Beslut                                    1586 non-null   str
dtypes: float64(2), int64(6), object(4), str(11)
memory usage: 534.5+ KB

### Change of data type

The data type in the column "Beviljade platser totalt" was changed to integer (int) to enable numerical calculations and analyses.

In [8]:
resultat_2021["Beviljade platser totalt"] = resultat_2021["Beviljade platser totalt"].astype(int)
resultat_2021["Beviljade platser totalt"].dtype

dtype('int64')

# 2022

In [9]:
resultat_2022 = pd.read_excel("data/resultat-ansokningsomgang-2022.xlsx", sheet_name=5)

resultat_2022.sample(10)
resultat_2022.info()

,Utbildningsområde,Utbildningsnamn,Beslut,Diarienummer,Län,Kommun,Flera kommuner,Antal kommuner,YH-poäng,Studieform,...,Utbildningsanordnare administrativ enhet,Huvudmannatyp,Sökta platser per utbildningsomgång,Sökta platser totalt,Beviljade platser utbildningsomgång 1,Beviljade platser utbildningsomgång 2,Beviljade platser utbildningsomgång 3,Beviljade platser utbildningsomgång 4,Beviljade platser utbildningsomgång 5,Beviljade platser totalt
139,Data/IT,Frontendutvecklare inriktning tillgänglighet,Avslag,MYH 2022/5019,Västra Götaland,Göteborg,Nej,1,400,Distans,...,Folkuniversitetet Kursverksamheten vid Götebor...,Privat,35,105,0.0,0.0,0,0,0,0.0
949,Hälso- och sjukvård samt socialt arbete,Tandsköterska,Avslag,MYH 2022/4861,Jönköping,Gislaved,Ja,2,325,Bunden,...,Folkuniversitetet - Kursverksamheten vid Stock...,Privat,15,30,0.0,0.0,0,0,0,0.0
257,Data/IT,Mjukvaruutvecklare inbyggda system,Avslag,MYH 2022/4331,Stockholm,Solna,Ja,2,400,Distans,...,Hermods AB Umeå,Privat,15,60,0.0,0.0,0,0,0,0.0
1297,Samhällsbyggnad och byggteknik,Solenergiprojektör,Beviljad,MYH 2022/4548,Västra Götaland,Uddevalla,Ja,3,400,Bunden,...,Campus Varberg/Varbergs kommun,Kommun,5,25,5.0,5.0,5,0,0,15.0
397,"Ekonomi, administration och försäljning",Affärsinriktad Redovisningsekonom,Beviljad,MYH 2022/4546,Västra Götaland,Göteborg,Nej,1,425,Bunden,...,Plushögskolan AB - Affärshögskolan,Privat,35,105,35.0,35.0,35,0,0,105.0
1480,Teknik och tillverkning,Laborant,Beviljad,MYH 2022/4482,Halland,Varberg,Ja,3,400,Bunden,...,Lidköpings kommun Campus Lidköping,Kommun,9,45,9.0,9.0,9,0,0,27.0
1290,Samhällsbyggnad och byggteknik,Projektledare VVS,Beviljad,MYH 2022/5068,Västmanland,Västerås,Ja,2,200,Distans,...,Lernia Utbildning AB,Privat,10,20,10.0,10.0,0,0,0,20.0
816,Hälso- och sjukvård samt socialt arbete,Socialpedagog,Avslag,MYH 2022/4372,Jämtland,Östersund,Ja,3,400,Distans,...,Hermods AB Östersund,Privat,10,40,0.0,0.0,0,0,0,0.0
1302,Samhällsbyggnad och byggteknik,Teknisk förvaltare,Avslag,MYH 2022/5132,Stockholm,Stockholm,Nej,1,400,Bunden,...,Newton Kompetensutveckling AB,Privat,32,96,0.0,0.0,0,0,0,0.0
928,Hälso- och sjukvård samt socialt arbete,Stödpedagog inom funktionshinderområdet,Beviljad,MYH 2022/4276,Västra Götaland,Göteborg,Nej,1,200,Distans,...,Hermods AB Göteborg,Privat,35,140,35.0,35.0,35,0,0,105.0

<class 'pandas.DataFrame'>
RangeIndex: 1621 entries, 0 to 1620
Data columns (total 22 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Utbildningsområde                         1621 non-null   str
 1   Utbildningsnamn                           1621 non-null   str
 2   Beslut                                    1621 non-null   str
 3   Diarienummer                              1621 non-null   str
 4   Län                                       1621 non-null   str
 5   Kommun                                    1621 non-null   str
 6   Flera kommuner                            1621 non-null   str
 7   Antal kommuner                            1621 non-null   int64
 8   YH-poäng                                  1621 non-null   int64
 9   Studieform                                1621 non-null   str
 10  Studietakt %                              1621 non-null   int64
 11  Typ av examen                             1621 non-null   str
 12  Utbildningsanordnare administrativ enhet  1621 non-null   str
 13  Huvudmannatyp                             1621 non-null   str
 14  Sökta platser per utbildningsomgång       1621 non-null   int64
 15  Sökta platser totalt                      1621 non-null   int64
 16  Beviljade platser utbildningsomgång 1     1621 non-null   float64
 17  Beviljade platser utbildningsomgång 2     1621 non-null   float64
 18  Beviljade platser utbildningsomgång 3     1621 non-null   int64
 19  Beviljade platser utbildningsomgång 4     1621 non-null   int64
 20  Beviljade platser utbildningsomgång 5     1621 non-null   int64
 21  Beviljade platser totalt                  1621 non-null   float64
dtypes: float64(3), int64(8), str(11)
memory usage: 525.2 KB

In [10]:
resultat_2022["Beviljade platser totalt"] = resultat_2022["Beviljade platser totalt"].astype(int)
resultat_2022["Beviljade platser totalt"].dtype

dtype('int64')

# 2023

In [11]:
resultat_2023_1 = pd.read_excel("data/resultat-ansokningsomgang-2023.xlsx", sheet_name=4, header=5)
resultat_2023_2 = pd.read_excel("data/resultat-ansokningsomgang-2023.xlsx", sheet_name=5, header=5)

In [12]:
resultat_2023_1.columns.tolist()
resultat_2023_2.columns.tolist()

['Utbildningsområde',
 'SUN5 inriktning',
 'SUN5 inriktning namn',
 'Utbildningsnamn',
 'Beslut',
 'Diarienummer',
 'Flera kommuner',
 'Antal kommuner',
 'Län',
 'Kommun',
 'YH-poäng',
 'Studieform',
 'Studietakt %',
 'Typ av examen',
 'SeQF nivå',
 'Smalt yrkesområde',
 'Utbildningsanordnare administrativ enhet',
 'Huvudmannatyp',
 'Sökta utbildningsomgångar',
 'Beviljade utbildningsomgångar',
 'Sökta platser per utbildningsomgång',
 'Sökta platser totalt',
 'Beviljade platser utbildningsomgång 1',
 'Beviljade platser utbildningsomgång 2',
 'Beviljade platser utbildningsomgång 3',
 'Beviljade platser utbildningsomgång 4',
 'Beviljade platser utbildningsomgång 5',
 'Beviljade platser totalt']

['Utbildningsområde',
 'SUN5 inriktning',
 'SUN5 inriktning namn',
 'Utbildningsnamn',
 'Beslut',
 'Diarienummer',
 'Län',
 'Kommun',
 'Antal kommuner']

In [13]:
single = resultat_2023_1[resultat_2023_1["Kommun"] != "Flera kommuner"].copy()

In [14]:
multiple = resultat_2023_1[resultat_2023_1["Kommun"] == "Flera kommuner"].copy()

In [15]:
multiple = multiple.drop(
    columns=["Kommun", "Län", "Antal kommuner"]
)

In [16]:
expanded = multiple.merge(
    resultat_2023_2[
        ["Diarienummer", "Län", "Kommun", "Antal kommuner"]
    ],
    on="Diarienummer",
    how="left"
)

In [17]:
expanded["Beviljade platser totalt"] = (
    expanded["Beviljade platser totalt"] / expanded["Antal kommuner"]
).round().astype(int)

In [18]:
resultat_2023 = pd.concat(
    [single, expanded],
    ignore_index=True
)

The total number of granted places decreased from 40,702 to 40,680 after allocation and rounding. The difference of 22 places (0.05%) is due to rounding and is considered acceptable.

In [19]:
resultat_2023["Beviljade platser totalt"].sum()

np.int64(40680)

# 2024

In [20]:
resultat_2024_1 = pd.read_excel("data/resultat-ansokningsomgang-2024.xlsx", sheet_name=4, header=5)
resultat_2024_2 = pd.read_excel("data/resultat-ansokningsomgang-2024.xlsx", sheet_name=5, header=5)

In [21]:
resultat_2024_1.columns.tolist()
resultat_2024_2.columns.tolist()

['Utbildningsområde',
 'SUN5 inriktning',
 'SUN5 inriktning namn',
 'Utbildningsnamn',
 'Beslut',
 'Diarienummer',
 'Flera kommuner',
 'Antal kommuner',
 'Län',
 'Kommun',
 'YH-poäng',
 'Studieform',
 'Studietakt %',
 'Typ av examen',
 'SeQF nivå',
 'Smalt yrkesområde',
 'Utbildningsanordnare administrativ enhet',
 'Huvudmannatyp',
 'Sökta utbildningsomgångar',
 'Beviljade utbildningsomgångar',
 'Sökta platser per utbildningsomgång',
 'Sökta platser totalt',
 'Beviljade platser utbildningsomgång 1',
 'Beviljade platser utbildningsomgång 2',
 'Beviljade platser utbildningsomgång 3',
 'Beviljade platser utbildningsomgång 4',
 'Beviljade platser utbildningsomgång 5',
 'Beviljade platser totalt']

['Utbildningsområde',
 'SUN5 inriktning',
 'SUN5 inriktning namn',
 'Utbildningsnamn',
 'Beslut',
 'Diarienummer',
 'Län',
 'Kommun',
 'Antal kommuner']

In [22]:
single_24 = resultat_2024_1[resultat_2024_1["Kommun"] != "Flera kommuner"].copy()

In [23]:
multiple_24 = resultat_2024_1[resultat_2024_1["Kommun"] == "Flera kommuner"].copy()

In [24]:
multiple_24 = multiple_24.drop(
    columns=["Kommun", "Län", "Antal kommuner"]
)

In [25]:
expanded_24 = multiple_24.merge(
    resultat_2024_2[
        ["Diarienummer", "Län", "Kommun", "Antal kommuner"]
    ],
    on="Diarienummer",
    how="left"
)

In [26]:
expanded_24["Beviljade platser totalt"] = (
    expanded_24["Beviljade platser totalt"] / expanded_24["Antal kommuner"]
).round().astype(int)

In [27]:
resultat_2024 = pd.concat(
    [single_24, expanded_24],
    ignore_index=True
)

The total number of granted places decreased from 40,702 to 29,358 after allocation and rounding. The difference of 16 places (0.05%) is due to rounding and is considered acceptable.

In [28]:
resultat_2024["Beviljade platser totalt"].sum()

np.int64(29342)

# 2025

In [29]:
resultat_2025_1 = pd.read_excel("data/resultat-ansokningsomgang-2025.xlsx", sheet_name=4, header=6)
resultat_2025_2 = pd.read_excel("data/resultat-ansokningsomgang-2025.xlsx", sheet_name=5, header=6)

In [30]:
single_25 = resultat_2025_1[resultat_2025_1["Kommun"] != "Flera kommuner"].copy()

In [31]:
multiple_25 = resultat_2025_1[resultat_2025_1["Kommun"] == "Flera kommuner"].copy()

In [32]:
multiple_25 = multiple_25.drop(
    columns=["Kommun", "Län", "Antal kommuner"]
)

In [33]:
expanded_25 = multiple_25.merge(
    resultat_2025_2[
        ["Diarienummer", "Län", "Kommun", "Antal kommuner"]
    ],
    on="Diarienummer",
    how="left"
)

In [34]:
expanded_25["Beviljade platser totalt"] = (
    expanded_25["Beviljade platser totalt"] / expanded_25["Antal kommuner"]
).round().astype(int)

In [35]:
resultat_2025 = pd.concat(
    [single_25, expanded_25],
    ignore_index=True
)

From 37,972 to 37958. 14 places

In [36]:
resultat_2025["Beviljade platser totalt"].sum()

np.int64(37958)

## Normalization of the variable beslut (decision)
Kolumnen beslut normaliserades för att säkerställa en enhetlig kategorisering över hela tidsperioden. I data för åren 2020–2021 användes värdena “beviljad” och “ej beviljad”, medan senare år innehöll kategorierna “beviljad” och “Avslag”. För att skapa en konsekvent variabel ersattes värdet “ej beviljad” med “Avslag”. Efter normaliseringen innehåller kolumnen endast två kategorier: “Beviljad” och “Avslag”.

In [37]:
resultat = {
    2020: resultat_2020,
    2021: resultat_2021,
    2022: resultat_2022,
    2023: resultat_2023,
    2024: resultat_2024,
    2025: resultat_2025
}
for year, df in resultat.items():
    print(year)
    print(sorted(df["Beslut"].unique()))
    print()

2020
['Beviljad', 'Ej beviljad']

2021
['Beviljad', 'Ej beviljad']

2022
['Avslag', 'Beviljad']

2023
['Avslag', 'Beviljad']

2024
['Avslag', 'Beviljad']

2025
['Avslag', 'Beviljad', 'Återkallad']

In [38]:
resultat_2020["Beslut"] = resultat_2020["Beslut"].replace(
    {"Ej beviljad": "Avslag"}
)
resultat_2021["Beslut"] = resultat_2021["Beslut"].replace(
    {"Ej beviljad": "Avslag"}
)

### Create a dictionary for column names

A dictionary with new column names was created and used to rename selected variables. The purpose was to have uniform column names in all DataFrames before the continued analysis.

In [39]:
rename_dict = {
    "Diarienummer": "case_number",
    "Utbildningsnamn": "education_name",
    "Utbildningsområde": "education_area",
    "Beslut": "decision",
    "Kommun": "municipality",
    "Län": "county",
    "YH-poäng": "education_credits",
    "Studieform": "study_mode",
    "Studietakt %": "study_pace_percentage",
    "Utbildningsanordnare administrativ enhet": "education_provider",
    "Huvudmannatyp": "principal_type",
    "SUN5 inriktning": "sun5_code",
    "SUN5 inriktning namn": "sun5_name",
    "SeQF nivå": "seqf_level",
    "Smalt yrkesområde": "narrow_occupational_area",
    "Sökta platser totalt": "total_sought_places",
    "Beviljade platser totalt": "total_granted_places"
}

In [40]:
resultat_2020 = resultat_2020.rename(columns=rename_dict)
resultat_2020["source_year"] = 2020
resultat_2020["source_file"] = "resultat-ansokningsomgang-2020.xlsx"
resultat_2020["source_sheet"] = "Tabell 3, 4"

resultat_2021 = resultat_2021.rename(columns=rename_dict)
resultat_2021["source_year"] = 2021
resultat_2021["source_file"] = "resultat-ansokningsomgang-2021.xlsx"
resultat_2021["source_sheet"] = "Tabell 3, 4"

resultat_2022 = resultat_2022.rename(columns=rename_dict)
resultat_2022["source_year"] = 2022
resultat_2022["source_file"] = "resultat-ansokningsomgang-2022.xlsx"
resultat_2022["source_sheet"] = "Tabell 3, 4"

resultat_2023 = resultat_2023.rename(columns=rename_dict)
resultat_2023["source_year"] = 2023
resultat_2023["source_file"] = "resultat-ansokningsomgang-2023.xlsx"
resultat_2023["source_sheet"] = "Tabell 3"

resultat_2024 = resultat_2024.rename(columns=rename_dict)
resultat_2024["source_year"] = 2024
resultat_2024["source_file"] = "resultat-ansokningsomgang-2024.xlsx"
resultat_2024["source_sheet"] = "Tabell 3"

resultat_2025 = resultat_2025.rename(columns=rename_dict)
resultat_2025["source_year"] = 2025
resultat_2025["source_file"] = "resultat-ansokningsomgang-2025.xlsx"
resultat_2025["source_sheet"] = "Tabell 3"

In [41]:
resultat_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   education_area                         1725 non-null   str
 1   sun5_code                              1725 non-null   str
 2   sun5_name                              1725 non-null   str
 3   education_name                         1725 non-null   str
 4   decision                               1725 non-null   str
 5   case_number                            1725 non-null   str
 6   Flera kommuner                         1725 non-null   str
 7   Antal kommuner                         1725 non-null   int64
 8   county                                 1725 non-null   str
 9   municipality                           1725 non-null   str
 10  education_credits                      1725 non-null   int64
 11  study_mode                             1725 non-null   str
 12  study_pace_percentage                  1725 non-null   int64
 13  Examenstyp                             1725 non-null   str
 14  seqf_level                             1702 non-null   float64
 15  narrow_occupational_area               1725 non-null   str
 16  education_provider                     1725 non-null   str
 17  principal_type                         1725 non-null   str
 18  Sökta utbildningsomgångar              1725 non-null   int64
 19  Beviljade utbildningsomgångar          1725 non-null   int64
 20  Sökta platser per utbildningsomgång    1725 non-null   int64
 21  total_sought_places                    1725 non-null   int64
 22  Beviljade platser utbildningsomgång 1  1725 non-null   int64
 23  Beviljade platser utbildningsomgång 2  1725 non-null   int64
 24  Beviljade platser utbildningsomgång 3  1725 non-null   int64
 25  Beviljade platser utbildningsomgång 4  1725 non-null   int64
 26  Beviljade platser utbildningsomgång 5  1725 non-null   int64
 27  total_granted_places                   1725 non-null   int64
 28  source_year                            1725 non-null   int64
 29  source_file                            1725 non-null   str
 30  source_sheet                           1725 non-null   str
dtypes: float64(1), int64(14), str(16)
memory usage: 850.5 KB

### Create column structure

A list of all variables to be included in the final analysis was created (main_columns). Since the variables sun5_inriktning, sun5_inriktning_namn, seqf_nivå and smalt_yrkesområde only exist for the years 2023–2025, reindex() was used to give all DataFrames the same column structure before merging the data.
If a variable was missing for a certain year, the column was automatically created with empty values (NaN). This facilitated the subsequent merging of data from different years.

In [42]:
main_columns = [
    "source_year",
    "source_file",
    "source_sheet",
    "case_number",
    "education_name",
    "education_area",
    "decision",
    "municipality",
    "county",
    "education_credits",
    "study_mode",
    "study_pace_percentage",
    "education_provider",
    "principal_type",
    "sun5_code",
    "sun5_name",
    "seqf_level",
    "narrow_occupational_area",
    "total_sought_places",
    "total_granted_places"
]

In [43]:
applications_2020 = resultat_2020.reindex(columns=main_columns)
applications_2021 = resultat_2021.reindex(columns=main_columns)
applications_2022 = resultat_2022.reindex(columns=main_columns)
applications_2023 = resultat_2023[main_columns]
applications_2024 = resultat_2024[main_columns]
applications_2025 = resultat_2025[main_columns]

In [44]:
unique_counts = pd.DataFrame({
    "2020": applications_2020.nunique(),
    "2021": applications_2021.nunique(),
    "2022": applications_2022.nunique(),
    "2023": applications_2023.nunique(),
    "2024": applications_2024.nunique(),
    "2025": applications_2025.nunique()
})
unique_counts.sort_values(by="2020", ascending=False)

                          2020  2021  2022  2023  2024  2025
case_number               1482  1238  1207  1258  1272  1184
education_name             965   902   851   896   851   836
education_provider         256   248   254   249   250   242
municipality               149   148   136   138   140   131
total_sought_places         64    66    64    44    43    42
education_credits           61    53    57    50    54    53
total_granted_places        50    44    52    43    38    42
county                      21    21    21    21    21    21
education_area              15    15    15    15    15    14
principal_type               4     4     4     4     4     3
study_pace_percentage        3     3     3     3     3     3
study_mode                   2     2     2     2     2     2
decision                     2     2     2     2     2     3
source_sheet                 1     1     1     1     1     1
source_year                  1     1     1     1     1     1
source_file                  1     1     1     1     1     1
sun5_name                    0     0     0   195   200   200
sun5_code                    0     0     0   195   200   200
narrow_occupational_area     0     0     0     2     2     2
seqf_level                   0     0     0     2     2     2

In [45]:
study_pace_percentage = pd.DataFrame({
    "2020": applications_2020["study_pace_percentage"].value_counts(),
    "2021": applications_2021["study_pace_percentage"].value_counts(),
    "2022": applications_2022["study_pace_percentage"].value_counts(),
    "2023": applications_2023["study_pace_percentage"].value_counts(),
    "2024": applications_2024["study_pace_percentage"].value_counts(),
    "2025": applications_2025["study_pace_percentage"].value_counts()
})
study_pace_percentage

                       2020  2021  2022  2023  2024  2025
study_pace_percentage
100                    1675  1404  1445  1473  1663  1558
50                      194   151   136   151   125   131
75                       34    31    40    33    34    36

## Merging data from all years

After all DataFrames had been given the same column structure, they were merged into a common DataFrame using the function pd.concat(). Data for the years 2020–2025 was thereby combined into one table, which enabled analyses across the entire time period.

In [46]:
applications = pd.concat(
    [applications_2020,
    applications_2021,
    applications_2022,
    applications_2023,
    applications_2024,
    applications_2025],
    ignore_index=True
)

In [47]:
applications.info()

<class 'pandas.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   source_year               10314 non-null  int64
 1   source_file               10314 non-null  str
 2   source_sheet              10314 non-null  str
 3   case_number               10314 non-null  str
 4   education_name            10314 non-null  str
 5   education_area            10314 non-null  str
 6   decision                  10314 non-null  str
 7   municipality              10314 non-null  str
 8   county                    10314 non-null  str
 9   education_credits         10314 non-null  int64
 10  study_mode                10314 non-null  str
 11  study_pace_percentage     10314 non-null  int64
 12  education_provider        10314 non-null  str
 13  principal_type            10314 non-null  str
 14  sun5_code                 5204 non-null   object
 15  sun5_name                 5204 non-null   object
 16  seqf_level                5141 non-null   float64
 17  narrow_occupational_area  5204 non-null   object
 18  total_sought_places       10314 non-null  int64
 19  total_granted_places      10314 non-null  int64
dtypes: float64(1), int64(5), object(3), str(11)
memory usage: 3.4+ MB

In [48]:
applications["sun5_code"] = applications["sun5_code"].astype("string")
applications["sun5_name"] = applications["sun5_name"].astype("string")
applications["seqf_level"] = applications["seqf_level"].astype("string")

In [49]:
applications[["sun5_code", "sun5_name", "narrow_occupational_area"]].sample(20)

,sun5_code,sun5_name,narrow_occupational_area
4038,<NA>,<NA>,NaN
2467,<NA>,<NA>,NaN
328,<NA>,<NA>,NaN
7135,345ac,Ledarskapsutbildningar inom vård,Nej
1940,<NA>,<NA>,NaN
8212,213dc,Utbildningar inom medieproduktion,Nej
7185,349zn,Utbildningar inom ekonomi med inriktning mot l...,Nej
9850,321ba,Utbildningar inom kommunikation,Nej
3311,<NA>,<NA>,NaN
2838,<NA>,<NA>,NaN
5978,522ca,Utbildningar till elinstallatör,Nej
6927,481xe,Utbildningar inom dataanalys och datavetenskap,Nej
6481,762ca,Utbildningar till behandlingsassistent/behandl...,Nej
8774,341za,Utbildningar inom inköp och offentlig upphandling,Nej
874,<NA>,<NA>,NaN
113,<NA>,<NA>,NaN
611,<NA>,<NA>,NaN
2116,<NA>,<NA>,NaN
3183,<NA>,<NA>,NaN
3913,<NA>,<NA>,NaN

### Data Enrichment

New columns were created from existing variables to make the dataset more useful for analysis and API consumers:

- `is_approved` – boolean flag for approved applications
- `is_distance` – boolean flag for distance education
- `program_length_years` – estimated program length in years based on YH credits

In [50]:
applications["is_approved"] = applications["decision"] == "Beviljad"

applications["is_distance"] = applications["study_mode"] == "Distans"

applications["program_length_years"] = (applications["education_credits"] / 200).round(1)

applications.sample(10)

,source_year,source_file,source_sheet,case_number,education_name,education_area,decision,municipality,county,education_credits,...,principal_type,sun5_code,sun5_name,seqf_level,narrow_occupational_area,total_sought_places,total_granted_places,is_approved,is_distance,program_length_years
2516,2021,resultat-ansokningsomgang-2021.xlsx,"Tabell 3, 4",MYH 2021/3567,Redovisningskonsult,"Ekonomi, administration och försäljning",Beviljad,Stockholm,Stockholm,410,...,Privat,<NA>,<NA>,<NA>,NaN,105,105,True,True,2.0
6105,2023,resultat-ansokningsomgang-2023.xlsx,Tabell 3,MYH 2023/4133,Lokförare Borlänge,Transporttjänster,Avslag,Borlänge,Dalarna,220,...,Privat,840ba,Utbildningar till lokförare,5.0,Nej,60,0,False,False,1.1
2376,2021,resultat-ansokningsomgang-2021.xlsx,"Tabell 3, 4",MYH 2021/3054,Företagssäljare/B2B,"Ekonomi, administration och försäljning",Avslag,Östersund,Jämtland,400,...,Privat,<NA>,<NA>,<NA>,NaN,120,0,False,True,2.0
6697,2023,resultat-ansokningsomgang-2023.xlsx,Tabell 3,MYH 2023/3790,Elingenjör/Elkonstruktör,Teknik och tillverkning,Beviljad,Borås,Västra Götaland,400,...,Kommun,522cd,Utbildningar till elkonstruktör,5.0,Nej,100,30,True,False,2.0
6270,2023,resultat-ansokningsomgang-2023.xlsx,Tabell 3,MYH 2023/4382,Network Engineer - Nätverksspecialist,Data/IT,Avslag,Luleå,Norrbotten,400,...,Privat,489zd,Utbildningar till IT-infrastukturtekniker,5.0,Nej,140,0,False,False,2.0
9081,2025,resultat-ansokningsomgang-2025.xlsx,Tabell 3,MYH 2025/4033,Internationell Kulturproducent,"Kultur, media och design",Beviljad,Boden,Norrbotten,400,...,Privat,210zy,Övriga utbildningar inom konst och media,5.0,Nej,90,90,True,True,2.0
9403,2025,resultat-ansokningsomgang-2025.xlsx,Tabell 3,MYH 2025/3908,Automationsingenjör,Teknik och tillverkning,Avslag,Gävle,Gävleborg,410,...,Privat,523fa,Utbildningar till automationstekniker,6.0,Nej,60,0,False,True,2.0
7155,2024,resultat-ansokningsomgang-2024.xlsx,Tabell 3,MYH 2024/3251,Rekryteringsspecialist - Internationell inrikt...,"Ekonomi, administration och försäljning",Avslag,Stockholm,Stockholm,400,...,Privat,345cy,Övriga utbildningar personal- och löneadminist...,5.0,Nej,105,0,False,False,2.0
7536,2024,resultat-ansokningsomgang-2024.xlsx,Tabell 3,MYH 2024/3088,Drifttekniker,Samhällsbyggnad och byggteknik,Avslag,Sundsvall,Västernorrland,400,...,Privat,582xa,Utbildningar till fastighetstekniker,5.0,Nej,75,0,False,True,2.0
9055,2025,resultat-ansokningsomgang-2025.xlsx,Tabell 3,MYH 2025/3352,Socialpedagog,Hälso- och sjukvård samt socialt arbete,Avslag,Stockholm,Stockholm,400,...,Privat,762ca,Utbildningar till behandlingsassistent/behandl...,5.0,Nej,105,0,False,False,2.0

In [51]:
applications.info()

<class 'pandas.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   source_year               10314 non-null  int64
 1   source_file               10314 non-null  str
 2   source_sheet              10314 non-null  str
 3   case_number               10314 non-null  str
 4   education_name            10314 non-null  str
 5   education_area            10314 non-null  str
 6   decision                  10314 non-null  str
 7   municipality              10314 non-null  str
 8   county                    10314 non-null  str
 9   education_credits         10314 non-null  int64
 10  study_mode                10314 non-null  str
 11  study_pace_percentage     10314 non-null  int64
 12  education_provider        10314 non-null  str
 13  principal_type            10314 non-null  str
 14  sun5_code                 5204 non-null   string
 15  sun5_name                 5204 non-null   string
 16  seqf_level                5141 non-null   string
 17  narrow_occupational_area  5204 non-null   object
 18  total_sought_places       10314 non-null  int64
 19  total_granted_places      10314 non-null  int64
 20  is_approved               10314 non-null  bool
 21  is_distance               10314 non-null  bool
 22  program_length_years      10314 non-null  float64
dtypes: bool(2), float64(1), int64(5), object(1), str(11), string(3)
memory usage: 3.7+ MB

In [52]:
applications.groupby("source_year")[["total_sought_places", "total_granted_places"]].sum()

             total_sought_places  total_granted_places
source_year
2020                      167448                 39758
2021                      131369                 35130
2022                      131176                 35086
2023                      193811                 40680
2024                      199995                 29342
2025                      177582                 37958

In [53]:
applications["narrow_occupational_area"].unique()

array([nan, 'Nej', 'Ja'], dtype=object)

In [54]:
applications["narrow_occupational_area"] = applications["narrow_occupational_area"].map({"Ja": True, "Nej": False})
applications["narrow_occupational_area"] = applications["narrow_occupational_area"].astype("boolean")

In [55]:
applications.loc[applications["program_length_years"]==2.0, ["education_credits", "program_length_years"]].value_counts()

education_credits  program_length_years
400                2.0                     4823
410                2.0                      270
405                2.0                       46
390                2.0                       10
406                2.0                        1
401                2.0                        1
Name: count, dtype: int64

In [56]:
applications["education_credits"].value_counts()

education_credits
400    4823
200    1082
300     985
420     307
425     270
       ...
999       1
130       1
355       1
540       1
525       1
Name: count, Length: 89, dtype: int64

In [57]:
applications[["seqf_level", "narrow_occupational_area"]].value_counts()

seqf_level  narrow_occupational_area
5.0         False                       5009
6.0         False                         87
5.0         True                          45
Name: count, dtype: int64

In [58]:
applications["seqf_level"].unique()
applications.groupby("source_year")["study_mode"].value_counts()

<ArrowStringArray>
[<NA>, '5.0', '6.0']
Length: 3, dtype: string

source_year  study_mode
2020         Bunden        1102
             Distans        801
2021         Bunden         897
             Distans        689
2022         Bunden         811
             Distans        810
2023         Bunden         853
             Distans        804
2024         Distans       1032
             Bunden         790
2025         Distans        970
             Bunden         755
Name: count, dtype: int64

In [59]:
applications["education_area"].value_counts()
applications["education_area"].unique()

education_area
Data/IT                                         2240
Ekonomi, administration och försäljning         2015
Teknik och tillverkning                         1657
Samhällsbyggnad och byggteknik                  1582
Hälso- och sjukvård samt socialt arbete         1177
Kultur, media och design                         338
Hotell, restaurang och turism                    325
Lantbruk, djurvård, trädgård, skog och fiske     230
Säkerhetstjänster                                190
Pedagogik och undervisning                       189
Transporttjänster                                181
Journalistik och information                      65
Friskvård och kroppsvård                          63
Juridik                                           53
Övrigt                                             9
Name: count, dtype: int64

<ArrowStringArray>
[                                     'Data/IT',
      'Ekonomi, administration och försäljning',
                     'Friskvård och kroppsvård',
                'Hotell, restaurang och turism',
      'Hälso- och sjukvård samt socialt arbete',
                 'Journalistik och information',
                                      'Juridik',
                     'Kultur, media och design',
 'Lantbruk, djurvård, trädgård, skog och fiske',
                   'Pedagogik och undervisning',
               'Samhällsbyggnad och byggteknik',
                            'Säkerhetstjänster',
                      'Teknik och tillverkning',
                            'Transporttjänster',
                                       'Övrigt']
Length: 15, dtype: str

In [60]:
applications["education_area"] = applications["education_area"].str.strip().str.title()

In [61]:
applications["principal_type"].unique()
applications["principal_type"].value_counts()

<ArrowStringArray>
['Privat', 'Kommun', 'Landsting', 'Statlig', 'Region']
Length: 5, dtype: str

principal_type
Privat       8707
Kommun       1508
Region         63
Landsting      23
Statlig        13
Name: count, dtype: int64

### Normalization of categories in principal_type

The variable principal_type contained the categories Privat, Kommun, Landsting, Statlig och Region. Landsting and Region refer to the same type of regional principal, these categories were harmonized by replacing the value Landsting with Region. This resulted in a more consistent classification in the dataset.

In [62]:
applications["principal_type"] = applications["principal_type"].replace({"Landsting": "Region"})

In [63]:
applications["principal_type"].unique()

<ArrowStringArray>
['Privat', 'Kommun', 'Region', 'Statlig']
Length: 4, dtype: str

In [64]:
applications.info()

<class 'pandas.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   source_year               10314 non-null  int64
 1   source_file               10314 non-null  str
 2   source_sheet              10314 non-null  str
 3   case_number               10314 non-null  str
 4   education_name            10314 non-null  str
 5   education_area            10314 non-null  str
 6   decision                  10314 non-null  str
 7   municipality              10314 non-null  str
 8   county                    10314 non-null  str
 9   education_credits         10314 non-null  int64
 10  study_mode                10314 non-null  str
 11  study_pace_percentage     10314 non-null  int64
 12  education_provider        10314 non-null  str
 13  principal_type            10314 non-null  str
 14  sun5_code                 5204 non-null   string
 15  sun5_name                 5204 non-null   string
 16  seqf_level                5141 non-null   string
 17  narrow_occupational_area  5204 non-null   boolean
 18  total_sought_places       10314 non-null  int64
 19  total_granted_places      10314 non-null  int64
 20  is_approved               10314 non-null  bool
 21  is_distance               10314 non-null  bool
 22  program_length_years      10314 non-null  float64
dtypes: bool(2), boolean(1), float64(1), int64(5), str(11), string(3)
memory usage: 3.6 MB

In [65]:
applications["education_provider"].unique()

<ArrowStringArray>
[                                         'KYH AB',
                                    'KYH AB Malmö',
                 'ABF Göteborg Vuxenutbildning AB',
              'Plushögskolan AB - Teknikhögskolan',
                       'IT-Högskolan Stockholm AB',
                         'IT-Högskolan Sverige AB',
                                  'Campus Mölndal',
                             'YrkesAkademin YH AB',
 'Sveriges Yrkeshögskola AB - Malmö Yrkeshögskola',
                                     'Edugrade AB',
 ...
                           'Chas Academy Extended',
                                      'Xe Drix AB',
                                'Arisone Medic AB',
              'Sveriges Kommunikatörer Aktiebolag',
                                'Origo Academy AB',
                        'Alea Kompetenshöjning AB',
                               'Distanslära DL AB',
                   'Hvilan Utbildning - Stockholm',
                   'Ingenjörshögskolan Sverige AB',
               'Scandinavian Edtech Production AB']
Length: 551, dtype: str

In [66]:
applications["education_provider"] = applications["education_provider"].str.strip().str.title()
applications["education_provider"].unique()

<ArrowStringArray>
[                                         'Kyh Ab',
                                    'Kyh Ab Malmö',
                 'Abf Göteborg Vuxenutbildning Ab',
              'Plushögskolan Ab - Teknikhögskolan',
                       'It-Högskolan Stockholm Ab',
                         'It-Högskolan Sverige Ab',
                                  'Campus Mölndal',
                             'Yrkesakademin Yh Ab',
 'Sveriges Yrkeshögskola Ab - Malmö Yrkeshögskola',
                                     'Edugrade Ab',
 ...
                     'Digit Utbildning Sverige Ab',
                           'Chas Academy Extended',
                                      'Xe Drix Ab',
                                'Arisone Medic Ab',
              'Sveriges Kommunikatörer Aktiebolag',
                                'Origo Academy Ab',
                               'Distanslära Dl Ab',
                   'Hvilan Utbildning - Stockholm',
                   'Ingenjörshögskolan Sverige Ab',
               'Scandinavian Edtech Production Ab']
Length: 531, dtype: str

In [67]:
applications.info()

<class 'pandas.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   source_year               10314 non-null  int64
 1   source_file               10314 non-null  str
 2   source_sheet              10314 non-null  str
 3   case_number               10314 non-null  str
 4   education_name            10314 non-null  str
 5   education_area            10314 non-null  str
 6   decision                  10314 non-null  str
 7   municipality              10314 non-null  str
 8   county                    10314 non-null  str
 9   education_credits         10314 non-null  int64
 10  study_mode                10314 non-null  str
 11  study_pace_percentage     10314 non-null  int64
 12  education_provider        10314 non-null  str
 13  principal_type            10314 non-null  str
 14  sun5_code                 5204 non-null   string
 15  sun5_name                 5204 non-null   string
 16  seqf_level                5141 non-null   string
 17  narrow_occupational_area  5204 non-null   boolean
 18  total_sought_places       10314 non-null  int64
 19  total_granted_places      10314 non-null  int64
 20  is_approved               10314 non-null  bool
 21  is_distance               10314 non-null  bool
 22  program_length_years      10314 non-null  float64
dtypes: bool(2), boolean(1), float64(1), int64(5), str(11), string(3)
memory usage: 3.6 MB

In [68]:
kommuner = pd.read_excel("data/kommunlankod-2026.xlsx", header=5)

c:\Users\dinar\Desktop\Py\Hemtenta\venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [69]:
kommuner.head()

   Code            Name
0     1  Stockholms län
1   114  Upplands Väsby
2   115      Vallentuna
3   117       Österåker
4   120          Värmdö

In [70]:
kommuner["Code"] = kommuner["Code"].astype(str)

In [71]:
lan = kommuner[kommuner["Code"].str.len() <= 2].copy()
kommun = kommuner[kommuner["Code"].str.len() > 2].copy()

In [72]:
kommuner

     Code            Name
0       1  Stockholms län
1     114  Upplands Väsby
2     115      Vallentuna
3     117       Österåker
4     120          Värmdö
..    ...             ...
306  2580           Luleå
307  2581           Piteå
308  2582           Boden
309  2583       Haparanda
310  2584          Kiruna

[311 rows x 2 columns]

In [73]:
lan["lankod"] = lan["Code"].str.zfill(2)
kommun["kommunkod"] = kommun["Code"].str.zfill(4)
kommun["lankod"] = kommun["kommunkod"].str[:2]

In [74]:
lan
kommun

    Code                  Name lankod
0      1        Stockholms län     01
27     3           Uppsala län     03
36     4     Södermanlands län     04
46     5     Östergötlands län     05
60     6        Jönköpings län     06
74     7        Kronobergs län     07
83     8            Kalmar län     08
96     9          Gotlands län     09
98    10          Blekinge län     10
104   12             Skåne län     12
138   13          Hallands län     13
145   14  Västra Götalands län     14
195   17         Värmlands län     17
212   18            Örebro län     18
225   19      Västmanlands län     19
236   20          Dalarnas län     20
252   21        Gävleborgs län     21
263   22   Västernorrlands län     22
271   23         Jämtlands län     23
280   24     Västerbottens län     24
296   25       Norrbottens län     25

     Code            Name kommunkod lankod
1     114  Upplands Väsby      0114     01
2     115      Vallentuna      0115     01
3     117       Österåker      0117     01
4     120          Värmdö      0120     01
5     123        Järfälla      0123     01
..    ...             ...       ...    ...
306  2580           Luleå      2580     25
307  2581           Piteå      2581     25
308  2582           Boden      2582     25
309  2583       Haparanda      2583     25
310  2584          Kiruna      2584     25

[290 rows x 4 columns]

In [75]:
lan = lan.rename(
    columns={
        "Name": "lan"
    }
)[["lankod", "lan"]]
kommun = kommun.rename(
    columns={
        "Name": "kommun"
    }
)[["kommunkod", "kommun", "lankod"]]

In [76]:
lan

    lankod                   lan
0       01        Stockholms län
27      03           Uppsala län
36      04     Södermanlands län
46      05     Östergötlands län
60      06        Jönköpings län
74      07        Kronobergs län
83      08            Kalmar län
96      09          Gotlands län
98      10          Blekinge län
104     12             Skåne län
138     13          Hallands län
145     14  Västra Götalands län
195     17         Värmlands län
212     18            Örebro län
225     19      Västmanlands län
236     20          Dalarnas län
252     21        Gävleborgs län
263     22   Västernorrlands län
271     23         Jämtlands län
280     24     Västerbottens län
296     25       Norrbottens län

In [77]:
lan["county"] = (
    lan["lan"]
    .str.replace("s län", "", regex=False)
    .str.replace(" län", "", regex=False)
)

In [78]:
lan

    lankod                   lan           county
0       01        Stockholms län        Stockholm
27      03           Uppsala län          Uppsala
36      04     Södermanlands län     Södermanland
46      05     Östergötlands län     Östergötland
60      06        Jönköpings län        Jönköping
74      07        Kronobergs län        Kronoberg
83      08            Kalmar län           Kalmar
96      09          Gotlands län          Gotland
98      10          Blekinge län         Blekinge
104     12             Skåne län            Skåne
138     13          Hallands län          Halland
145     14  Västra Götalands län  Västra Götaland
195     17         Värmlands län         Värmland
212     18            Örebro län           Örebro
225     19      Västmanlands län      Västmanland
236     20          Dalarnas län          Dalarna
252     21        Gävleborgs län        Gävleborg
263     22   Västernorrlands län   Västernorrland
271     23         Jämtlands län         Jämtland
280     24     Västerbottens län     Västerbotten
296     25       Norrbottens län       Norrbotten

In [79]:
set(lan["county"].dropna().unique()) - set(applications["county"].dropna().unique())

set()

In [80]:
kommun = kommun.merge(
    lan,
    on="lankod",
    how="left"
)

In [81]:
kommun.head()

  kommunkod          kommun lankod             lan     county
0      0114  Upplands Väsby     01  Stockholms län  Stockholm
1      0115      Vallentuna     01  Stockholms län  Stockholm
2      0117       Österåker     01  Stockholms län  Stockholm
3      0120          Värmdö     01  Stockholms län  Stockholm
4      0123        Järfälla     01  Stockholms län  Stockholm

In [82]:
kommun = kommun.rename(
    columns={
        "kommunkod": "municipality_code",
        "kommun": "municipality",
        "lankod": "county_code"
    }
)

In [83]:
kommun = kommun.drop(columns={"lan"})

In [84]:
kommun

    municipality_code    municipality county_code      county
0                0114  Upplands Väsby          01   Stockholm
1                0115      Vallentuna          01   Stockholm
2                0117       Österåker          01   Stockholm
3                0120          Värmdö          01   Stockholm
4                0123        Järfälla          01   Stockholm
..                ...             ...         ...         ...
285              2580           Luleå          25  Norrbotten
286              2581           Piteå          25  Norrbotten
287              2582           Boden          25  Norrbotten
288              2583       Haparanda          25  Norrbotten
289              2584          Kiruna          25  Norrbotten

[290 rows x 4 columns]

In [85]:
print(kommun.columns)
print(len(kommun))

Index(['municipality_code', 'municipality', 'county_code', 'county'], dtype='str')
290

In [86]:
municipalities = kommun.copy()

In [87]:
municipalities.head()

  municipality_code    municipality county_code     county
0              0114  Upplands Väsby          01  Stockholm
1              0115      Vallentuna          01  Stockholm
2              0117       Österåker          01  Stockholm
3              0120          Värmdö          01  Stockholm
4              0123        Järfälla          01  Stockholm

In [88]:
municipalities.to_csv("data/municipalities.csv", index=False)

In [89]:
countys = lan.drop(columns={"lan"})

In [90]:
countys

    lankod           county
0       01        Stockholm
27      03          Uppsala
36      04     Södermanland
46      05     Östergötland
60      06        Jönköping
74      07        Kronoberg
83      08           Kalmar
96      09          Gotland
98      10         Blekinge
104     12            Skåne
138     13          Halland
145     14  Västra Götaland
195     17         Värmland
212     18           Örebro
225     19      Västmanland
236     20          Dalarna
252     21        Gävleborg
263     22   Västernorrland
271     23         Jämtland
280     24     Västerbotten
296     25       Norrbotten

In [91]:
countys = countys.rename(
    columns={
        "lankod": "county_code",
        "county": "county"
    }
)

In [92]:
countys.to_csv("data/countys.csv", index=False)

In [93]:
municipalities.head()

  municipality_code    municipality county_code     county
0              0114  Upplands Väsby          01  Stockholm
1              0115      Vallentuna          01  Stockholm
2              0117       Österåker          01  Stockholm
3              0120          Värmdö          01  Stockholm
4              0123        Järfälla          01  Stockholm

In [94]:
applications.loc[
    applications["municipality"] == "Malung",
    "municipality"
] = "Malung-Sälen"
applications.loc[
    applications["municipality"] == "Upplands-Väsby",
    "municipality"
] = "Upplands Väsby"

In [95]:
applications = applications.merge(
    municipalities[
        [
            "municipality_code",
            "municipality",
            "county_code",
            "county"
        ]
    ],
    on=["municipality", "county"],
    how="left"
)

In [96]:
applications[
    [
            "municipality",
            "county",
            "municipality_code",
            "county_code"
    ]
].sample(20)

      municipality      county municipality_code county_code
1135         Sunne    Värmland              1766          17
990       Halmstad     Halland              1380          13
10163    Stockholm   Stockholm              0180          01
2033     Norrtälje   Stockholm              0188          01
364          Sunne    Värmland              1766          17
7462     Stockholm   Stockholm              0180          01
9901     Norrtälje   Stockholm              0188          01
2348         Solna   Stockholm              0184          01
5989         Solna   Stockholm              0184          01
3091   Helsingborg       Skåne              1283          12
1884     Östersund    Jämtland              2380          23
202          Solna   Stockholm              0184          01
7678     Stockholm   Stockholm              0180          01
7153         Malmö       Skåne              1280          12
6527         Boden  Norrbotten              2582          25
2381        Kalmar      Kalmar              0880          08
2493     Stockholm   Stockholm              0180          01
1819     Jönköping   Jönköping              0680          06
5138         Solna   Stockholm              0184          01
6657      Borlänge     Dalarna              2081          20

In [97]:
population = pd.read_excel("data/population 2020-24.xlsx", header=2)

In [98]:
population

     Unnamed: 0      Unnamed: 1   2020   2021   2022   2023   2024
0           114  Upplands Väsby  47184  47820  49262  50110  50323
1           115      Vallentuna  34119  34246  34851  35076  35119
2           117       Österåker  46644  48234  49138  49282  49787
3           120          Värmdö  45566  46232  46457  46637  46635
4           123        Järfälla  81274  83170  85460  86330  88950
..          ...             ...    ...    ...    ...    ...    ...
285        2580           Luleå  78549  78867  79244  79352  79645
286        2581           Piteå  42226  42323  42362  42344  42447
287        2582           Boden  28060  28160  28048  27943  28049
288        2583       Haparanda   9601   9496   9340   9177   9151
289        2584          Kiruna  22664  22555  22423  22433  22426

[290 rows x 7 columns]

In [99]:
population_2025 = pd.read_excel("data/population 2025.xlsx", header=2)

In [100]:
population_2025

              Unnamed: 0   2025
0    0114 Upplands Väsby  50495
1        0115 Vallentuna  35361
2         0117 Österåker  49943
3            0120 Värmdö  46601
4          0123 Järfälla  90180
..                   ...    ...
285           2580 Luleå  80304
286           2581 Piteå  42184
287           2582 Boden  28624
288       2583 Haparanda   9027
289          2584 Kiruna  22402

[290 rows x 2 columns]

In [101]:
population_2025["kommunkod"] = (
    population_2025["Unnamed: 0"].str.extract(r"^(\d{4})")
)

In [102]:
population_2025

              Unnamed: 0   2025 kommunkod
0    0114 Upplands Väsby  50495      0114
1        0115 Vallentuna  35361      0115
2         0117 Österåker  49943      0117
3            0120 Värmdö  46601      0120
4          0123 Järfälla  90180      0123
..                   ...    ...       ...
285           2580 Luleå  80304      2580
286           2581 Piteå  42184      2581
287           2582 Boden  28624      2582
288       2583 Haparanda   9027      2583
289          2584 Kiruna  22402      2584

[290 rows x 3 columns]

In [103]:
population_2025.head()
population.head()

            Unnamed: 0   2025 kommunkod
0  0114 Upplands Väsby  50495      0114
1      0115 Vallentuna  35361      0115
2       0117 Österåker  49943      0117
3          0120 Värmdö  46601      0120
4        0123 Järfälla  90180      0123

   Unnamed: 0      Unnamed: 1   2020   2021   2022   2023   2024
0         114  Upplands Väsby  47184  47820  49262  50110  50323
1         115      Vallentuna  34119  34246  34851  35076  35119
2         117       Österåker  46644  48234  49138  49282  49787
3         120          Värmdö  45566  46232  46457  46637  46635
4         123        Järfälla  81274  83170  85460  86330  88950

In [104]:
population["kommunkod"] = (population["Unnamed: 0"].astype(str).str.zfill(4))

In [105]:
population = population.rename(columns={"Unnamed: 1": "kommun"})

In [106]:
population = population.merge(population_2025[["kommunkod", "2025"]], on="kommunkod", how="left")

In [107]:
population.head()

,Unnamed: 0,kommun,2020,2021,2022,2023,2024,kommunkod,2025
0,114,Upplands Väsby,47184,47820,49262,50110,50323,0114,50495
1,115,Vallentuna,34119,34246,34851,35076,35119,0115,35361
2,117,Österåker,46644,48234,49138,49282,49787,0117,49943
3,120,Värmdö,45566,46232,46457,46637,46635,0120,46601
4,123,Järfälla,81274,83170,85460,86330,88950,0123,90180

In [108]:
population = population.drop(columns=["Unnamed: 0"])

In [109]:
population.head()

           kommun   2020   2021   2022   2023   2024 kommunkod   2025
0  Upplands Väsby  47184  47820  49262  50110  50323      0114  50495
1      Vallentuna  34119  34246  34851  35076  35119      0115  35361
2       Österåker  46644  48234  49138  49282  49787      0117  49943
3          Värmdö  45566  46232  46457  46637  46635      0120  46601
4        Järfälla  81274  83170  85460  86330  88950      0123  90180

In [110]:
population_long = population.melt(
    id_vars=["kommunkod", "kommun"],
    value_vars=["2020", "2021", "2022", "2023", "2024", "2025"],
    var_name="year",
    value_name="population"
)

In [111]:
population_long["year"] = population_long["year"].astype(int)
population_long["population"] = population_long["population"].astype(int)

In [112]:
population_long = population_long.rename(
    columns={
        "kommunkod": "municipality_code",
        "kommun": "municipality",
        "year": "year",
        "population": "population"
    }
)

In [113]:
population_long

     municipality_code    municipality  year  population
0                 0114  Upplands Väsby  2020       47184
1                 0115      Vallentuna  2020       34119
2                 0117       Österåker  2020       46644
3                 0120          Värmdö  2020       45566
4                 0123        Järfälla  2020       81274
...                ...             ...   ...         ...
1735              2580           Luleå  2025       80304
1736              2581           Piteå  2025       42184
1737              2582           Boden  2025       28624
1738              2583       Haparanda  2025        9027
1739              2584          Kiruna  2025       22402

[1740 rows x 4 columns]

In [114]:
population_long.to_csv("data/population_2020-2025.csv", index=False)

In [115]:
applications.to_csv("data/applications.csv", index=False)

In [116]:
applications.info()

<class 'pandas.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   source_year               10314 non-null  int64
 1   source_file               10314 non-null  str
 2   source_sheet              10314 non-null  str
 3   case_number               10314 non-null  str
 4   education_name            10314 non-null  str
 5   education_area            10314 non-null  str
 6   decision                  10314 non-null  str
 7   municipality              10314 non-null  str
 8   county                    10314 non-null  str
 9   education_credits         10314 non-null  int64
 10  study_mode                10314 non-null  str
 11  study_pace_percentage     10314 non-null  int64
 12  education_provider        10314 non-null  str
 13  principal_type            10314 non-null  str
 14  sun5_code                 5204 non-null   string
 15  sun5_name                 5204 non-null   string
 16  seqf_level                5141 non-null   string
 17  narrow_occupational_area  5204 non-null   boolean
 18  total_sought_places       10314 non-null  int64
 19  total_granted_places      10314 non-null  int64
 20  is_approved               10314 non-null  bool
 21  is_distance               10314 non-null  bool
 22  program_length_years      10314 non-null  float64
 23  municipality_code         10314 non-null  str
 24  county_code               10314 non-null  str
dtypes: bool(2), boolean(1), float64(1), int64(5), str(13), string(3)
memory usage: 3.9 MB

In [117]:
applications["county_code"].value_counts()

county_code
01    2507
14    2002
12    1444
24     504
05     399
25     382
06     369
22     341
07     249
21     233
18     233
17     226
19     218
04     208
13     192
08     176
20     165
03     145
10     143
23     127
09      51
Name: count, dtype: int64

In [118]:
population_long.columns.tolist()

['municipality_code', 'municipality', 'year', 'population']

In [119]:
applications.columns.tolist()

['source_year',
 'source_file',
 'source_sheet',
 'case_number',
 'education_name',
 'education_area',
 'decision',
 'municipality',
 'county',
 'education_credits',
 'study_mode',
 'study_pace_percentage',
 'education_provider',
 'principal_type',
 'sun5_code',
 'sun5_name',
 'seqf_level',
 'narrow_occupational_area',
 'total_sought_places',
 'total_granted_places',
 'is_approved',
 'is_distance',
 'program_length_years',
 'municipality_code',
 'county_code']

In [120]:
applications["county_code"].isna().sum()

np.int64(0)

In [121]:
applications["municipality_code"].unique()

<ArrowStringArray>
['2380', '0780', '1280', '0188', '0483', '0428', '1480', '0180', '1481',
 '1488',
 ...
 '1463', '0126', '1257', '2404', '0319', '0642', '2031', '2034', '1261',
 '0584']
Length: 205, dtype: str

In [122]:
municipalities.columns

Index(['municipality_code', 'municipality', 'county_code', 'county'], dtype='str')

In [123]:
len(applications)

10314

In [124]:
applications["case_number"].nunique()

7641

In [125]:
applications.columns.tolist()

['source_year',
 'source_file',
 'source_sheet',
 'case_number',
 'education_name',
 'education_area',
 'decision',
 'municipality',
 'county',
 'education_credits',
 'study_mode',
 'study_pace_percentage',
 'education_provider',
 'principal_type',
 'sun5_code',
 'sun5_name',
 'seqf_level',
 'narrow_occupational_area',
 'total_sought_places',
 'total_granted_places',
 'is_approved',
 'is_distance',
 'program_length_years',
 'municipality_code',
 'county_code']

In [126]:
county["county"].tolist()

NameError: name 'county' is not defined

In [ ]:
applications["education_area"].unique()

<ArrowStringArray>
[                                     'Data/It',
      'Ekonomi, Administration Och Försäljning',
                     'Friskvård Och Kroppsvård',
                'Hotell, Restaurang Och Turism',
      'Hälso- Och Sjukvård Samt Socialt Arbete',
                 'Journalistik Och Information',
                                      'Juridik',
                     'Kultur, Media Och Design',
 'Lantbruk, Djurvård, Trädgård, Skog Och Fiske',
                   'Pedagogik Och Undervisning',
               'Samhällsbyggnad Och Byggteknik',
                            'Säkerhetstjänster',
                      'Teknik Och Tillverkning',
                            'Transporttjänster',
                                       'Övrigt']
Length: 15, dtype: str

In [ ]:
applications["sun5_name"].unique()

<ArrowStringArray>
[                                                            <NA>,
                          'Utbildningar till programmerare, spel',
            'Utbildningar inom systemhantering och programmering',
        'Utbildningar inom inbyggda system och sakernas internet',
                            'Utbildningar till databasutvecklare',
                               'Utbildningar till webbutvecklare',
                              'Utbildningar till mjukvarutestare',
         'Övriga utbildningar systemutveckling och programmering',
                        'Utbildningar till systemadministratörer',
                 'Utbildningar inom dataanalys och datavetenskap',
 ...
                      'Utbildningar till drifttekniker fastighet',
                          'Övriga utbildningar säkerhetstjänster',
                     'Utbildningar till yrkessvetsare, avancerad',
 'Utbildningar till svetsspecialist, kontrollant och konstruktör',
                  'Utbildningar till järnvägstekniker/eltekniker',
 'Övriga utbildningar elektronik-, tele- och datatekniskt arbete',
                                  'Utbildningar till sadelmakare',
                                     'Utbildningar till skeppare',
                              'Övriga utbildningar fordonsteknik',
                             'Utbildningar till bryggeritekniker']
Length: 250, dtype: string

In [ ]:
total = applications[applications["source_year"].isin([2023, 2024, 2025])]["total_granted_places"].sum()
total

np.int64(107980)

In [128]:
applications["principal_type"].unique()

<ArrowStringArray>
['Privat', 'Kommun', 'Region', 'Statlig']
Length: 4, dtype: str

In [127]:
applications["county"].unique()

<ArrowStringArray>
[       'Jämtland',       'Kronoberg',           'Skåne',       'Stockholm',
    'Södermanland', 'Västra Götaland',       'Gävleborg',    'Västerbotten',
        'Värmland',      'Norrbotten',        'Blekinge',          'Kalmar',
  'Västernorrland',     'Västmanland',         'Uppsala',       'Jönköping',
         'Dalarna',          'Örebro',    'Östergötland',         'Halland',
         'Gotland']
Length: 21, dtype: str